package grails.plugins.timeseries.gorm

class TimeSeriesAggregate {
	String refId
	String metric
	String resolution
	Integer duration = 0
	Integer count = 0
	Double total = 0
	Date start
	Date end

	Integer count0
	Integer count1
	Integer count2
	Integer count3
	Integer count4
	Integer count5
	Integer count6
	Integer count7
	Integer count8
	Integer count9
	Integer count10
	Integer count11
	Integer count12
	Integer count13
	Integer count14
	Integer count15
	Integer count16
	Integer count17
	Integer count18
	Integer count19
	Integer count20
	Integer count21
	Integer count22
	Integer count23
	Integer count24
	Integer count25
	Integer count26
	Integer count27
	Integer count28
	Integer count29
	Integer count30
	Integer count31
	Integer count32
	Integer count33
	Integer count34
	Integer count35
	Integer count36
	Integer count37
	Integer count38
	Integer count39
	Integer count40
	Integer count41
	Integer count42
	Integer count43
	Integer count44
	Integer count45
	Integer count46
	Integer count47
	Integer count48
	Integer count49
	Integer count50
	Integer count51
	Integer count52
	Integer count53
	Integer count54
	Integer count55
	Integer count56
	Integer count57
	Integer count58
	Integer count59
	Integer count60
	Integer count61
	Integer count62
	Integer count63
	Integer count64
	Integer count65
	Integer count66
	Integer count67
	Integer count68
	Integer count69
	Integer count70
	Integer count71
	Integer count72
	Integer count73
	Integer count74
	Integer count75
	Integer count76
	Integer count77
	Integer count78
	Integer count79
	Integer count80
	Integer count81
	Integer count82
	Integer count83
	Integer count84
	Integer count85
	Integer count86
	Integer count87
	Integer count88
	Integer count89
	Integer count90
	Integer count91
	Integer count92
	Integer count93
	Integer count94
	Integer count95

	Double total0
	Double total1
	Double total2
	Double total3
	Double total4
	Double total5
	Double total6
	Double total7
	Double total8
	Double total9
	Double total10
	Double total11
	Double total12
	Double total13
	Double total14
	Double total15
	Double total16
	Double total17
	Double total18
	Double total19
	Double total20
	Double total21
	Double total22
	Double total23
	Double total24
	Double total25
	Double total26
	Double total27
	Double total28
	Double total29
	Double total30
	Double total31
	Double total32
	Double total33
	Double total34
	Double total35
	Double total36
	Double total37
	Double total38
	Double total39
	Double total40
	Double total41
	Double total42
	Double total43
	Double total44
	Double total45
	Double total46
	Double total47
	Double total48
	Double total49
	Double total50
	Double total51
	Double total52
	Double total53
	Double total54
	Double total55
	Double total56
	Double total57
	Double total58
	Double total59
	Double total60
	Double total61
	Double total62
	Double total63
	Double total64
	Double total65
	Double total66
	Double total67
	Double total68
	Double total69
	Double total70
	Double total71
	Double total72
	Double total73
	Double total74
	Double total75
	Double total76
	Double total77
	Double total78
	Double total79
	Double total80
	Double total81
	Double total82
	Double total83
	Double total84
	Double total85
	Double total86
	Double total87
	Double total88
	Double total89
	Double total90
	Double total91
	Double total92
	Double total93
	Double total94
	Double total95

    static constraints = {
	count0 nullable:true
	count1 nullable:true
	count2 nullable:true
	count3 nullable:true
	count4 nullable:true
	count5 nullable:true
	count6 nullable:true
	count7 nullable:true
	count8 nullable:true
	count9 nullable:true
	count10 nullable:true
	count11 nullable:true
	count12 nullable:true
	count13 nullable:true
	count14 nullable:true
	count15 nullable:true
	count16 nullable:true
	count17 nullable:true
	count18 nullable:true
	count19 nullable:true
	count20 nullable:true
	count21 nullable:true
	count22 nullable:true
	count23 nullable:true
	count24 nullable:true
	count25 nullable:true
	count26 nullable:true
	count27 nullable:true
	count28 nullable:true
	count29 nullable:true
	count30 nullable:true
	count31 nullable:true
	count32 nullable:true
	count33 nullable:true
	count34 nullable:true
	count35 nullable:true
	count36 nullable:true
	count37 nullable:true
	count38 nullable:true
	count39 nullable:true
	count40 nullable:true
	count41 nullable:true
	count42 nullable:true
	count43 nullable:true
	count44 nullable:true
	count45 nullable:true
	count46 nullable:true
	count47 nullable:true
	count48 nullable:true
	count49 nullable:true
	count50 nullable:true
	count51 nullable:true
	count52 nullable:true
	count53 nullable:true
	count54 nullable:true
	count55 nullable:true
	count56 nullable:true
	count57 nullable:true
	count58 nullable:true
	count59 nullable:true
	count60 nullable:true
	count61 nullable:true
	count62 nullable:true
	count63 nullable:true
	count64 nullable:true
	count65 nullable:true
	count66 nullable:true
	count67 nullable:true
	count68 nullable:true
	count69 nullable:true
	count70 nullable:true
	count71 nullable:true
	count72 nullable:true
	count73 nullable:true
	count74 nullable:true
	count75 nullable:true
	count76 nullable:true
	count77 nullable:true
	count78 nullable:true
	count79 nullable:true
	count80 nullable:true
	count81 nullable:true
	count82 nullable:true
	count83 nullable:true
	count84 nullable:true
	count85 nullable:true
	count86 nullable:true
	count87 nullable:true
	count88 nullable:true
	count89 nullable:true
	count90 nullable:true
	count91 nullable:true
	count92 nullable:true
	count93 nullable:true
	count94 nullable:true
	count95 nullable:true
	total0 nullable:true
	total1 nullable:true
	total2 nullable:true
	total3 nullable:true
	total4 nullable:true
	total5 nullable:true
	total6 nullable:true
	total7 nullable:true
	total8 nullable:true
	total9 nullable:true
	total10 nullable:true
	total11 nullable:true
	total12 nullable:true
	total13 nullable:true
	total14 nullable:true
	total15 nullable:true
	total16 nullable:true
	total17 nullable:true
	total18 nullable:true
	total19 nullable:true
	total20 nullable:true
	total21 nullable:true
	total22 nullable:true
	total23 nullable:true
	total24 nullable:true
	total25 nullable:true
	total26 nullable:true
	total27 nullable:true
	total28 nullable:true
	total29 nullable:true
	total30 nullable:true
	total31 nullable:true
	total32 nullable:true
	total33 nullable:true
	total34 nullable:true
	total35 nullable:true
	total36 nullable:true
	total37 nullable:true
	total38 nullable:true
	total39 nullable:true
	total40 nullable:true
	total41 nullable:true
	total42 nullable:true
	total43 nullable:true
	total44 nullable:true
	total45 nullable:true
	total46 nullable:true
	total47 nullable:true
	total48 nullable:true
	total49 nullable:true
	total50 nullable:true
	total51 nullable:true
	total52 nullable:true
	total53 nullable:true
	total54 nullable:true
	total55 nullable:true
	total56 nullable:true
	total57 nullable:true
	total58 nullable:true
	total59 nullable:true
	total60 nullable:true
	total61 nullable:true
	total62 nullable:true
	total63 nullable:true
	total64 nullable:true
	total65 nullable:true
	total66 nullable:true
	total67 nullable:true
	total68 nullable:true
	total69 nullable:true
	total70 nullable:true
	total71 nullable:true
	total72 nullable:true
	total73 nullable:true
	total74 nullable:true
	total75 nullable:true
	total76 nullable:true
	total77 nullable:true
	total78 nullable:true
	total79 nullable:true
	total80 nullable:true
	total81 nullable:true
	total82 nullable:true
	total83 nullable:true
	total84 nullable:true
	total85 nullable:true
	total86 nullable:true
	total87 nullable:true
	total88 nullable:true
	total89 nullable:true
	total90 nullable:true
	total91 nullable:true
	total92 nullable:true
	total93 nullable:true
	total94 nullable:true
	total95 nullable:true
    }
}
