package grails.plugins.timeseries.gorm

class TimeSeriesCounter {
	String refId
	String counter
	String resolution
	Boolean aggregate = false
	Integer duration = 0
	Double total = 0
	Date start
	Date end

	Double count0
	Double count1
	Double count2
	Double count3
	Double count4
	Double count5
	Double count6
	Double count7
	Double count8
	Double count9
	Double count10
	Double count11
	Double count12
	Double count13
	Double count14
	Double count15
	Double count16
	Double count17
	Double count18
	Double count19
	Double count20
	Double count21
	Double count22
	Double count23
	Double count24
	Double count25
	Double count26
	Double count27
	Double count28
	Double count29
	Double count30
	Double count31
	Double count32
	Double count33
	Double count34
	Double count35
	Double count36
	Double count37
	Double count38
	Double count39
	Double count40
	Double count41
	Double count42
	Double count43
	Double count44
	Double count45
	Double count46
	Double count47
	Double count48
	Double count49
	Double count50
	Double count51
	Double count52
	Double count53
	Double count54
	Double count55
	Double count56
	Double count57
	Double count58
	Double count59
	Double count60
	Double count61
	Double count62
	Double count63
	Double count64
	Double count65
	Double count66
	Double count67
	Double count68
	Double count69
	Double count70
	Double count71
	Double count72
	Double count73
	Double count74
	Double count75
	Double count76
	Double count77
	Double count78
	Double count79
	Double count80
	Double count81
	Double count82
	Double count83
	Double count84
	Double count85
	Double count86
	Double count87
	Double count88
	Double count89
	Double count90
	Double count91
	Double count92
	Double count93
	Double count94
	Double count95

	static mapping = {
		refId index: 'idx_st_ref_ct'
		aggregate index: 'idx_st_ref_ct'
		start index: 'idx_st_ref_ct'
		counter index: 'idx_st_ref_ct,idx_ed_ct'
		end index: 'idx_ed_ct'
	}

    static constraints = {
		count0 nullable:true
		count1 nullable:true
		count2 nullable:true
		count3 nullable:true
		count4 nullable:true
		count5 nullable:true
		count6 nullable:true
		count7 nullable:true
		count8 nullable:true
		count9 nullable:true
		count10 nullable:true
		count11 nullable:true
		count12 nullable:true
		count13 nullable:true
		count14 nullable:true
		count15 nullable:true
		count16 nullable:true
		count17 nullable:true
		count18 nullable:true
		count19 nullable:true
		count20 nullable:true
		count21 nullable:true
		count22 nullable:true
		count23 nullable:true
		count24 nullable:true
		count25 nullable:true
		count26 nullable:true
		count27 nullable:true
		count28 nullable:true
		count29 nullable:true
		count30 nullable:true
		count31 nullable:true
		count32 nullable:true
		count33 nullable:true
		count34 nullable:true
		count35 nullable:true
		count36 nullable:true
		count37 nullable:true
		count38 nullable:true
		count39 nullable:true
		count40 nullable:true
		count41 nullable:true
		count42 nullable:true
		count43 nullable:true
		count44 nullable:true
		count45 nullable:true
		count46 nullable:true
		count47 nullable:true
		count48 nullable:true
		count49 nullable:true
		count50 nullable:true
		count51 nullable:true
		count52 nullable:true
		count53 nullable:true
		count54 nullable:true
		count55 nullable:true
		count56 nullable:true
		count57 nullable:true
		count58 nullable:true
		count59 nullable:true
		count60 nullable:true
		count61 nullable:true
		count62 nullable:true
		count63 nullable:true
		count64 nullable:true
		count65 nullable:true
		count66 nullable:true
		count67 nullable:true
		count68 nullable:true
		count69 nullable:true
		count70 nullable:true
		count71 nullable:true
		count72 nullable:true
		count73 nullable:true
		count74 nullable:true
		count75 nullable:true
		count76 nullable:true
		count77 nullable:true
		count78 nullable:true
		count79 nullable:true
		count80 nullable:true
		count81 nullable:true
		count82 nullable:true
		count83 nullable:true
		count84 nullable:true
		count85 nullable:true
		count86 nullable:true
		count87 nullable:true
		count88 nullable:true
		count89 nullable:true
		count90 nullable:true
		count91 nullable:true
		count92 nullable:true
		count93 nullable:true
		count94 nullable:true
		count95 nullable:true
    }
}
